source 'https://rubygems.org'
ruby '2.0.0'
#ruby-gemset=railstutorial_rails_4_0

gem 'rails', '4.0.4'
gem 'jquery-rails', '3.0.4'
gem 'turbolinks'

group :development do
  gem 'sqlite3', '1.3.8'
end

group :development do
	gem 'rspec-rails', '2.0.1'
end

group :test do
	gem 'rspec', '2.0.1'
	gem 'webrat', '0.7.1'
end
